package com.tien.piholeconnect.ui.theme

import android.graphics.Color.rgb
import android.os.Build
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFB02D26)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD5)
val md_theme_light_onPrimaryContainer = Color(0xFF410002)
val md_theme_light_secondary = Color(0xFFBA1A20)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD6)
val md_theme_light_onSecondaryContainer = Color(0xFF410003)
val md_theme_light_tertiary = Color(0xFF126D27)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF9FF79F)
val md_theme_light_onTertiaryContainer = Color(0xFF002105)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A19)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A19)
val md_theme_light_surfaceVariant = Color(0xFFF5DDDA)
val md_theme_light_onSurfaceVariant = Color(0xFF534341)
val md_theme_light_outline = Color(0xFF857371)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEEC)
val md_theme_light_inverseSurface = Color(0xFF362F2E)
val md_theme_light_inversePrimary = Color(0xFFFFB4AB)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFB02D26)
val md_theme_light_outlineVariant = Color(0xFFD8C2BF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB4AB)
val md_theme_dark_onPrimary = Color(0xFF690005)
val md_theme_dark_primaryContainer = Color(0xFF8E1212)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD5)
val md_theme_dark_secondary = Color(0xFFFFB3AC)
val md_theme_dark_onSecondary = Color(0xFF680008)
val md_theme_dark_secondaryContainer = Color(0xFF930010)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD6)
val md_theme_dark_tertiary = Color(0xFF83DA85)
val md_theme_dark_onTertiary = Color(0xFF00390E)
val md_theme_dark_tertiaryContainer = Color(0xFF005318)
val md_theme_dark_onTertiaryContainer = Color(0xFF9FF79F)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A19)
val md_theme_dark_onBackground = Color(0xFFEDE0DE)
val md_theme_dark_surface = Color(0xFF201A19)
val md_theme_dark_onSurface = Color(0xFFEDE0DE)
val md_theme_dark_surfaceVariant = Color(0xFF534341)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BF)
val md_theme_dark_outline = Color(0xFFA08C8A)
val md_theme_dark_inverseOnSurface = Color(0xFF201A19)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DE)
val md_theme_dark_inversePrimary = Color(0xFFB02D26)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB4AB)
val md_theme_dark_outlineVariant = Color(0xFF534341)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFF6659)
val Info = Color(0xFF2196F3)
val Success = Color(0xFF66BB6A)
val Warning = Color(0xFFFFC107)
val light_Info = Color(0xFF0061A4)
val light_onInfo = Color(0xFFFFFFFF)
val light_InfoContainer = Color(0xFFD1E4FF)
val light_onInfoContainer = Color(0xFF001D36)
val dark_Info = Color(0xFF9ECAFF)
val dark_onInfo = Color(0xFF003258)
val dark_InfoContainer = Color(0xFF00497D)
val dark_onInfoContainer = Color(0xFFD1E4FF)
val light_Success = Color(0xFF126D27)
val light_onSuccess = Color(0xFFFFFFFF)
val light_SuccessContainer = Color(0xFF9FF79F)
val light_onSuccessContainer = Color(0xFF002105)
val dark_Success = Color(0xFF83DA85)
val dark_onSuccess = Color(0xFF00390E)
val dark_SuccessContainer = Color(0xFF005318)
val dark_onSuccessContainer = Color(0xFF9FF79F)
val light_Warning = Color(0xFF785900)
val light_onWarning = Color(0xFFFFFFFF)
val light_WarningContainer = Color(0xFFFFDF9E)
val light_onWarningContainer = Color(0xFF261A00)
val dark_Warning = Color(0xFFFABD00)
val dark_onWarning = Color(0xFF3F2E00)
val dark_WarningContainer = Color(0xFF5B4300)
val dark_onWarningContainer = Color(0xFFFFDF9E)

fun Color.toColorInt() = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
    rgb(this.red, this.green, this.blue)
} else {
    rgb((this.red * 255).toInt(), (this.green * 255).toInt(), (this.blue * 255).toInt())
}
