package com.tien.piholeconnect.ui.theme

import android.graphics.Color.rgb
import android.os.Build
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006B5A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF7AF8DB)
val md_theme_light_onPrimaryContainer = Color(0xFF00201A)
val md_theme_light_secondary = Color(0xFF4B635C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE8DF)
val md_theme_light_onSecondaryContainer = Color(0xFF06201A)
val md_theme_light_tertiary = Color(0xFF426277)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC7E7FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E2E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFA)
val md_theme_light_onBackground = Color(0xFF191C1B)
val md_theme_light_surface = Color(0xFFFAFDFA)
val md_theme_light_onSurface = Color(0xFF191C1B)
val md_theme_light_surfaceVariant = Color(0xFFDBE5E0)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4945)
val md_theme_light_outline = Color(0xFF6F7975)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1EF)
val md_theme_light_inverseSurface = Color(0xFF2E3130)
val md_theme_light_inversePrimary = Color(0xFF5BDBBF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006B5A)
val md_theme_light_outlineVariant = Color(0xFFBFC9C4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF5BDBBF)
val md_theme_dark_onPrimary = Color(0xFF00382E)
val md_theme_dark_primaryContainer = Color(0xFF005143)
val md_theme_dark_onPrimaryContainer = Color(0xFF7AF8DB)
val md_theme_dark_secondary = Color(0xFFB1CCC3)
val md_theme_dark_onSecondary = Color(0xFF1D352F)
val md_theme_dark_secondaryContainer = Color(0xFF334B45)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE8DF)
val md_theme_dark_tertiary = Color(0xFFAACBE3)
val md_theme_dark_onTertiary = Color(0xFF103447)
val md_theme_dark_tertiaryContainer = Color(0xFF2A4A5F)
val md_theme_dark_onTertiaryContainer = Color(0xFFC7E7FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1B)
val md_theme_dark_onBackground = Color(0xFFE1E3E0)
val md_theme_dark_surface = Color(0xFF191C1B)
val md_theme_dark_onSurface = Color(0xFFE1E3E0)
val md_theme_dark_surfaceVariant = Color(0xFF3F4945)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C4)
val md_theme_dark_outline = Color(0xFF89938F)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1B)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E0)
val md_theme_dark_inversePrimary = Color(0xFF006B5A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF5BDBBF)
val md_theme_dark_outlineVariant = Color(0xFF3F4945)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF004D40)
val Info = Color(0xFF29B6F6)
val Success = Color(0xFF66BB6A)
val Warning = Color(0xFFFFA726)
val light_Info = Color(0xFF00658D)
val light_onInfo = Color(0xFFFFFFFF)
val light_InfoContainer = Color(0xFFC6E7FF)
val light_onInfoContainer = Color(0xFF001E2D)
val dark_Info = Color(0xFF81CFFF)
val dark_onInfo = Color(0xFF00344B)
val dark_InfoContainer = Color(0xFF004C6B)
val dark_onInfoContainer = Color(0xFFC6E7FF)
val light_Success = Color(0xFF126D27)
val light_onSuccess = Color(0xFFFFFFFF)
val light_SuccessContainer = Color(0xFF9FF79F)
val light_onSuccessContainer = Color(0xFF002105)
val dark_Success = Color(0xFF83DA85)
val dark_onSuccess = Color(0xFF00390E)
val dark_SuccessContainer = Color(0xFF005318)
val dark_onSuccessContainer = Color(0xFF9FF79F)
val light_Warning = Color(0xFF865300)
val light_onWarning = Color(0xFFFFFFFF)
val light_WarningContainer = Color(0xFFFFDDB9)
val light_onWarningContainer = Color(0xFF2B1700)
val dark_Warning = Color(0xFFFFB961)
val dark_onWarning = Color(0xFF472A00)
val dark_WarningContainer = Color(0xFF663E00)
val dark_onWarningContainer = Color(0xFFFFDDB9)

fun Color.toColorInt() =
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        rgb(this.red, this.green, this.blue)
    } else {
        rgb((this.red * 255).toInt(), (this.green * 255).toInt(), (this.blue * 255).toInt())
    }
