default_platform(:android)

platform :android do
  properties = {
    "android.injected.signing.store.file" => ENV["KEYSTORE_FILE"],
    "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
    "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
    "android.injected.signing.key.password" => ENV["KEY_PASSWORD"],
  }

  lane :development do
    android_set_version_code(
      version_code: ENV["VERSION_CODE"],
      gradle_file: "app/build.gradle.kts"
    )
    android_set_version_name(
      version_name: ENV["VERSION_NAME"],
      gradle_file: "app/build.gradle.kts"
    )

    gradle(task: "clean bundleRelease", properties: properties)
    firebase_app_distribution(android_artifact_type: "AAB")

    gradle(task: "clean assembleRelease", properties: properties)
    copy_artifacts(artifacts: [lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]])
  end

  lane :release do
    android_set_version_code(
      version_code: google_play_track_version_codes(track: "internal").max + 1,
      gradle_file: "app/build.gradle.kts"
    )
    android_set_version_name(
      version_name: ENV["VERSION_NAME"],
      gradle_file: "app/build.gradle.kts"
    )

    gradle(task: "clean bundleRelease", properties: properties)
    upload_to_play_store(track: "internal")

    gradle(task: "clean assembleRelease", properties: properties)
    set_github_release(is_draft: true, upload_assets: [lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]])
  end
end
