name: Release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: Version Name
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Write keystore to file
        run: echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > $GITHUB_WORKSPACE/keystore.jks

      - run: bundle exec fastlane release
        env:
          SUPPLY_JSON_KEY_DATA: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS }}
          KEYSTORE_FILE: ${{ github.workspace }}/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          FL_SET_GITHUB_RELEASE_REPOSITORY_NAME: ${{ github.repository }}
          FL_GITHUB_RELEASE_API_BEARER: ${{ github.token }}
          FL_SET_GITHUB_RELEASE_TAG_NAME: v${{ github.event.inputs.versionName }}
          FL_SET_GITHUB_RELEASE_COMMITISH: ${{ github.sha }}
          VERSION_NAME: ${{ github.event.inputs.versionName }}
